<a href="https://colab.research.google.com/github/neelima-singh07/Amazon-basic-clone-/blob/main/IDS_notes_unit2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#creating arrays using numpy
arr1=np.array([[1,2,3],[4,5,6]])  #using np.array
print(arr1)

arr2=np.zeros((3,5))  #using zeros
print(arr2)

arr3=np.ones((4,5)); #using np.ones
print(arr3)



[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Numpy array manipulation
arr1=np.array([1,2,3,4,5,6])
print("orignal array",arr1)
#convert to 2 d array
arr2=arr1.reshape(3,2) #using reshape
print("reshaped array:",arr2)

#transpose
arr3=arr2.transpose()
print("Transposed array:",arr3)



orignal array [1 2 3 4 5 6]
reshaped array: [[1 2]
 [3 4]
 [5 6]]
Transposed array: [[1 3 5]
 [2 4 6]]


In [ ]:
#numpy mathematical functions

#1. add two arrays
arr1=np.array([1,2,3,45])
arr2=np.array([67,9,54,3])
arr_sum=np.add(arr1,arr2)
print(arr_sum)

#2. subtract
arr3=np.array([1,2,3,45])
arr4=np.array([67,9,54,3])
arr_sum2=np.subtract(arr1,arr2)
print(arr_sum2)

#3. sqrt
arr5=np.array([1,2,3,45])
arr_sqrt=np.sqrt(arr5)
print(arr_sqrt)



[68 11 57 48]
[-66  -7 -51  42]
[1.         1.41421356 1.73205081 6.70820393]


In [ ]:
#numpy stats function
arr1=np.array([1,2,3,45])
arr_mean=np.mean(arr1)
print(arr_mean)

arr2=np.array([1,2,3,45])
arr_median=np.median(arr1)
print(arr_median)

arr3=np.array([1,2,3,45])
arr_std=np.std(arr1)
print(arr_std)

arr4=np.array([1,2,3,45])
arr_var=np.var(arr1)
print(arr_var)

arr4=np.array([1,2,3,45])
arr_min=np.min(arr1)
print(arr_min)

arr5=np.array([1,2,3,45])
arr_max=np.max(arr1)
print(arr_max)

#calculating mode
from scipy import stats
arr6=np.array([1,2,3,45,2])
arr_mode=stats.mode(arr6)
print(arr_mode)

12.75
2.5
18.632968094214082
347.1875
1
45


In [ ]:
#numpy input ouput load
#save array in text file
arr1=np.array([1,2,3,45])
np.savetxt("arr1.txt",arr1)

#load array from text file
arr2=np.loadtxt("arr1.txt")
print(arr2)

[ 1.  2.  3. 45.]


In [ ]:
#modfying array methods
#1.modifying array elts using index
arr1=np.array([1,2,3,45])
arr1[0]=100
print(arr1)

#2.modify array elts using -ve idx
arr2=np.array([1,2,3,45])
arr2[-1]=100
print(arr2)
 #3. using slicing
arr1[1:3] = [20, 30]  # Replace values at indices 1 and 2
print(arr1)

#4.Using Boolean Masking
arr1[arr1 > 3] = 99  # Replace values greater than 3 with 99
print(arr1)

#5. using np.where()
arr1 = np.array([1, 2, 3, 4, 5])
arr1[np.where(arr1 > 3)] = 99  # Replace values greater than 3 with 99
print(arr1)



[100   2   3  45]
[  1   2   3 100]


In [ ]:
#2D matrix indexing
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[0,2])
print(arr1[1,3])
print(arr1[1,:])
print(arr1[:,0])

3
8
[5 6 7 8]
[1 5]


In [ ]:
#3d numpy indexing
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print()
print(arr1.shape)
print()
print(arr1[arr1>3])
print()
print(arr1[0,1,2])
print()
print(arr1[0,2,:])
print(arr1[0, :, :]) #complete array
print()
#array 2

arr2=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
print(arr2)
print()
print(arr2.shape)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

(1, 3, 3)

[4 5 6 7 8 9]

6

[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

(2, 2, 3)


In [ ]:
#slicing in arrray
#start,stop,step
#1. 1d array
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1[1:7:2])
print(arr1[1:]) #no comma
print(arr1[::-1])
print(arr1[-1:-5:-1])
print()
#modify array elts using slicing
#1. start parameter
print("second case")
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[:3]=100
print(arr1)
#2. stop

arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[2:]=100
print(arr1)

#3 using st stop
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[2:6]=100
print(arr1)

#4. using st stop step
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[2:8:2]=100
print(arr1)

#negative slicing
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[-3:]=100
print(arr1)
arr1[-3:-1]=100
print(arr1)

#2d array slicing



[2 4 6]
[2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[9 8 7 6]

second case
[100 100 100   4   5   6   7   8   9]
[  1   2 100 100 100 100 100 100 100]
[  1   2 100 100 100 100   7   8   9]
[  1   2 100   4 100   6 100   8   9]
[  1   2   3   4   5   6 100 100 100]
[  1   2   3   4   5   6 100 100 100]


In [ ]:
#Arthimetic operators
#1. add and sub
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)

#multi and divide
print(arr1*arr2)
print(arr1/arr2)

#exponetiation and modulus
print(arr1**arr2)
print(arr1%arr2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]
[1 2 3 4]


In [ ]:

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[4,5,6]])
print(np.concatenate((arr1,arr2),axis=0))
print(np.concatenate((arr1,arr2),axis=1))
print(np.cumsum(arr1,axis=0))
print(np.cumsum(arr1,axis=1))
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]
[[1 2 3 7 8 9]
 [4 5 6 4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[[1 2 3 7 8 9]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]
